# Generated by Django 4.2.16 on 2024-10-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Name')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('product_likes', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('product_pic', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
            ],
        ),
    ]
